# deploy-appservice-template.yml
# It deploys code into app services on Azure

parameters:
- name: environment # don't pass run-time variables
- name: subscription
- name: webAppRG
- name: webAppName
- name: artifactName
  default: drop

jobs:
- deployment: DeployAppService
  displayName: 'Deploy to App Service'
  environment: ${{ parameters.environment }}
  workspace:
    clean: all
  strategy: 
    runOnce:
      deploy:
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: ${{ parameters.artifactName }}
            pattern: drop/strapicms.zip
            targetPath: '$(System.DefaultWorkingDirectory)/publish'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: ${{ parameters.subscription }}
            appType: 'webAppLinux' #its webApp for windows based apps. webAppLinux for linux based apps
            packageForLinux: '$(System.DefaultWorkingDirectory)/publish/strapicms.zip'
            WebAppName: ${{ parameters.webAppName }}
            ResourceGroupName: ${{ parameters.webAppRG }}
            StartupCommand: 'npm start'
