# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript 

# Pipelibe only build docker image and uploads to Azure Container Registry @113136 NTT Azure Accoount

trigger:
- main

#what to clean up before the job runs (outputs | resources | all)
pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest
  demand: node.js

variables:
- group: PipelineVariableGroup
#Build & Deployment flags used for debugging & troubleshooting
- name: bBuildInfrastructure
  value: true 
- name: bDeployToDev
  value: true 
- name: bBuildDockerImage
  value: true 
#Pipeline Variables
- name: appServicePlan
  value: 'node-strapi-cms-sp' 
- name: appServicePrefix
  value: 'node-strapi-cms' 
- name: resourceGroup
  value: 'node-strapi-cms-rg' 
- name: resourceLocation
  value: 'West US 2' 
- name: subscription
  value: 'Visual Studio Enterprise Subscription - 113136' 
- name: artifactName
  value: 'drop'
#Terraform Storage Variables
- name: terraformContainer
  value: 'node-strapi-cms-terraform' 
- name: terraformStorageAccount
  value: 'terraformsabibhu2021' 
- name: terraformStorageRG
  value: 'terraformstoragergp' 
#Container & K8 Variables
- name: privateContainerRegistry
  value: 'docker-azure-registry-private'
- name: privateRepository
  value: 'node-strapi-cms'
- name: tagName
  value: 'latest'


stages:
- stage: Build
  displayName: "Compile Code"
  jobs:
  - job: Compile
    displayName: 'Compile NPM Code' 
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install NodeJS Runtime'
    - task: CopyFiles@2
      displayName: 'Copy application code to k8 folder'
      inputs:
        preserveTimestamp: true
        cleanTargetFolder: true  
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          *k8*.yaml
        targetFolder: '$(build.artifactstagingdirectory)/k8'
    - task: CopyFiles@2
      displayName: 'Copy application code to www folder'
      inputs:
        preserveTimestamp: true
        cleanTargetFolder: true  
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **
          !.github/**
          !.git/**
          !ssl/**
          !src/**
          !terraform/**
          !dal/csvdata/**
          !*.txt
          !*.yaml
          !*.cmd
          !*.sh
          !*.md
          !Jenkins*.*
          !tailwind*.*
          !babel*.*
          !sonar*.*
          !.dockerignore
          !.gitignore
          !Dockerfile
          !LICENSE
        targetFolder: '$(build.artifactstagingdirectory)/www'
    - task: ArchiveFiles@2
      displayName: 'Create a deployable zip file from the www folder'
      inputs:
        rootFolderOrFile: '$(build.artifactstagingdirectory)/www'
        archiveFile: '$(Build.ArtifactStagingDirectory)/strapi.zip' 
        replaceExistingArchive: true 
        includeRootFolder: false 
    - task: DeleteFiles@1
      displayName: 'Delete the staging www folder post zipping'
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)/www'
        Contents: |
          **
        RemoveSourceFolder: true       
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts & Binaries to the drop folder'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifact: ${{ variables.artifactName }}
        publishLocation: 'pipeline'
  
  - job: Dockerize
    displayName: 'Create a Docker Image & Publish to Azure Container Registry - 113136'
    pool:
      name: "MyBuildAgents"
      demand: node.js
    condition:  eq('${{ variables.bBuildDockerImage }}', true)
    dependsOn: Compile
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: ${{ variables.privateContainerRegistry }}



#- stage: Infrastructure
#  displayName: 'Setup Infrastrucure in Azure'
#  pool:
#    name: "MyBuildAgents"
#    vmImage: ubuntu-latest
#    demand: node.js
#  jobs:
#  - template: azure-setup-appservice.yaml
#    parameters:
#      subscription: $(subscription)
#      terraformstoragerg: $(terraformStorageRG)
#      terraformstorageaccount: $(terraformStorageAccount)
#      terraformcontainer: $(terraformContainer)

#- stage: QA
#  displayName: 'Deploy Code to QA Web App Service'
#  pool:
#    name: "MyBuildAgents"
#    vmImage: ubuntu-latest
#    demand: node.js
#  dependsOn: 
#  - Infrastructure
#  - Build
#  variables: 
#    Environment: QA
#  jobs:
#  - template: azure-deploy-appservice-template.yaml
#    parameters:
#      environment: ${{ variables.environment }} 
#      webAppRG: $(ResourceGroup)
#      subscription: $(subscription)
#      webAppName: '$(appServicePrefix)-qa'

- stage: Development
  displayName: 'Deploy Code to Development Kubernetes Cluster'
  condition: eq('${{ variables.bDeployToDev }}', true) 
  pool:
    name: "MyBuildAgents"
    demand: node.js
  dependsOn: 
  - Build
  variables: 
    Environment: Development
  jobs:
  - template: azure-subpipeline-deploy-to-prod-k8-cluster.yaml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: '${{ variables.appServicePrefix }}-dev'
      subscription: ${{ variables.subscription }}

